name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    linting:
        name: Static linting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Format check
              run: npm run format:check

            - name: Typecheck
              run: npx tsc --noEmit

    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Run Unit Tests
              run: npm test

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: '24'
                  cache: 'npm'

            - name: Install NPM dependencies
              run: npm ci

            - name: Build library
              run: npm run build

    inclusive-language:
        name: Inclusive Language
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: get-woke/woke-action@b2ec032c4a2c912142b38a6a453ad62017813ed0 # v0
              with:
                  fail-on-error: true
